# Generated by Django 2.0.1 on 2018-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180715_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_of_submission',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
