# Generated by Django 2.0.1 on 2018-07-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_submission_date_of_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Head'),
        ),
    ]
