# Generated by Django 2.0.1 on 2018-07-15 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20180715_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subm_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 15, 17, 21, 26, 396786)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date_of_submission',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
