# Generated by Django 2.0.1 on 2018-07-15 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20180715_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subm_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 15, 17, 32, 15, 451665)),
        ),
    ]
