# Generated by Django 2.0.1 on 2018-07-15 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20180715_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subm_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 15, 17, 56, 13, 146328)),
        ),
    ]
